### ISSUE TITLE
Geolocation errors

### ISSUE THREAD

**Issue by futuresoup** [mapseed/platform#456] opened 2016-09-19 16:33 UTC
On http://dev.heyduwamish.org - when you add a report and hit the `Set my location` button or the map's geolocation icon:
- [ ] On Chrome ~~for Android~~: it says "geolocation disabled for this page. Please adjust your browser settings."
- [ ] On Firefox ~~for Android~~: it works, but delivers a false timeout error message, despite the fact that the marker has been moved to the correct location.
- [ ] Declining geolocation access in Firefox will not fire a `locationerror` event.

**Comment by goldpbear** [comment] 2016-09-19 17:21
I think if you're seeing "geolocation disabled for this page" errors in Chrome you have to adjust your browser settings to allow geolocation. This isn't something we can control externally.

**Comment by futuresoup** [comment] 2016-09-19 21:01
The problem is that the prompt for asking if it's okay to share your location doesn't show up in the first place.

I tested this by going to google.com/maps. The site triggers a popup that says "www.google.com wants to use your device's location"  - BLOCK / ALLOW

For us on http://dev.heyduwamish.org - when you hit the SET MY LOCATION button, it fails to bring the permissions dialogue like google.com/maps does. Instead it jumps straight to the dialog that says "Geolocation is disabled for this page", essentially bypassing the permissons dialogue. 

It works fine on Firefox, and apparently Safari (?), but Chrome on Android is not working as far as I can tell

**Comment by futuresoup** [comment] 2016-09-19 21:09
Okay found the problem...we need https:// or we are out by default. See here:

[No HTTPS? Then say goodbye to geolocation in Chrome 50!](https://mobiforge.com/news-comment/no-https-then-bye-bye-geolocation-in-chrome-50)

**Comment by goldpbear** [comment] 2016-09-19 21:35
Interesting--I can confirm this behavior in Chrome (version 53) on mac. Firefox and Safari will still prompt for geolocation services though.

So it seems we'd need to host the site over HTTPS in order for Chrome to prompt for geolocation activation. It looks like this behavior is part of the "HTTPS everywhere" push.

**Comment by futuresoup** [comment] 2016-09-19 22:05
@goldpbear are you getting the false timeout issue in Firefox? It's a separate issue I think.

Basically the geolocation will work but then the browser delivers an error message saying the site took too long to respond

**Comment by goldpbear** [comment] 2016-09-19 23:26
@futuresoup yes, I'm seeing the same behavior in Firefox on mac.

There's another issue in Firefox too: on Chrome, denying geolocation access will fire leaflet's `locationerror` event, which we use to reset the dynamic form drag map instructions. But Firefox doesn't behave this way, and no `locationerror` event is fired after declining geolocation access.

I'm not sure at the moment what's causing these differences in Firefox. I'll look into it.

**Comment by goldpbear** [comment] 2016-09-19 23:34
Removed mobile tag as this issue affects desktop browsers as well.

**Comment by goldpbear** [comment] 2016-09-20 00:13
Update on the `locationerror` issue in Firefox: apparently, this behavior is by design (albeit [very contentiously](https://bugzilla.mozilla.org/show_bug.cgi?id=675533)). Selecting the "Not Now" option when asked to geolocate will just hide the prompt; no error callback is fired.

**Comment by LukeSwart** [comment] 2016-10-31 03:59
FYI we have a dev site with SSL set up on dev2.heyduwamish.org where we can test this issue. Note that this issue might be a duplicate of #394, where if we can fix #394, we can fix this issue as well.

**Comment by modulitos** [comment] 2018-02-05 01:38
I believe this is fixed now that we have SSL.

**Closed by modulitos** 2018-02-05 01:38 UTC
Labels: bug
